linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - contextcheck
    - bodyclose
    - noctx

issues:
  exclude-use-default: false
  exclude:
    - fmt\.F(print|println|fprint).*is not checked
    - os\.(Setenv|Unsetenv).*is not checked
